/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.yvonne.computerscienceia;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.*;
import java.util.*;

/**
 *
 * @author student
 */
public class addRecipe extends javax.swing.JFrame {
    private String addName=null;
    private String addD=null;
    private String addIn=null;
    private String addM=null;
    private String addCat=null;
    public addRecipe() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ImageIcon icon = new ImageIcon("/Users/student/Desktop/exitSymbol.png");
        exitButton = new javax.swing.JButton(icon);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nameF = new javax.swing.JTextField();
        descriptionF = new javax.swing.JTextField();
        ingredientsF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        methodF = new javax.swing.JTextArea();
        britishB = new javax.swing.JRadioButton();
        fastB = new javax.swing.JRadioButton();
        chineseB = new javax.swing.JRadioButton();
        italianB = new javax.swing.JRadioButton();
        europeanB = new javax.swing.JRadioButton();
        japaneseB = new javax.swing.JRadioButton();
        koreanB = new javax.swing.JRadioButton();
        vegetarianB = new javax.swing.JRadioButton();
        addButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(254, 127, 0));
        jPanel2.setForeground(new java.awt.Color(254, 127, 0));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Add Recipe");

        exitButton.setBorder(null);

        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(39, 39, 39))
        );

        jLabel1.setText("Recipe Name");

        jLabel2.setText("Description");

        jLabel3.setText("Ingredients");

        jLabel4.setText("Method");

        nameF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFActionPerformed(evt);
            }
        });

        methodF.setColumns(20);
        methodF.setRows(5);
        jScrollPane1.setViewportView(methodF);

        buttonGroup1.add(britishB);
        britishB.setText("British");
        britishB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                britishBActionPerformed(evt);
            }
        });

        buttonGroup1.add(fastB);
        fastB.setText("Fast&Easy");
        fastB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fastBActionPerformed(evt);
            }
        });

        buttonGroup1.add(chineseB);
        chineseB.setText("Chinese");
        chineseB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chineseBActionPerformed(evt);
            }
        });

        buttonGroup1.add(italianB);
        italianB.setText("Italian");

        buttonGroup1.add(europeanB);
        europeanB.setText("European");

        buttonGroup1.add(japaneseB);
        japaneseB.setText("Japanese");

        buttonGroup1.add(koreanB);
        koreanB.setText("Korean");

        buttonGroup1.add(vegetarianB);
        vegetarianB.setText("Vegetarian");
        vegetarianB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vegetarianBActionPerformed(evt);
            }
        });

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(britishB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chineseB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(europeanB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fastB))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(italianB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(japaneseB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(koreanB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vegetarianB))
                    .addComponent(jScrollPane1)
                    .addComponent(ingredientsF)
                    .addComponent(descriptionF)
                    .addComponent(nameF))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(descriptionF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ingredientsF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(britishB)
                    .addComponent(chineseB)
                    .addComponent(europeanB)
                    .addComponent(fastB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(italianB)
                    .addComponent(japaneseB)
                    .addComponent(koreanB)
                    .addComponent(vegetarianB))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFActionPerformed
        
    }//GEN-LAST:event_nameFActionPerformed

    private void fastBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fastBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fastBActionPerformed

    private void britishBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_britishBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_britishBActionPerformed

    private void vegetarianBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vegetarianBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vegetarianBActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        addName=nameF.getText();
        addD=descriptionF.getText();
        addIn=ingredientsF.getText();
        addM=methodF.getText();
        HashMap<JRadioButton, String> catMap = new HashMap<>();
        catMap.put(britishB, "British");
        catMap.put(chineseB, "Chinese");
        catMap.put(europeanB, "European");
        catMap.put(fastB, "Fast&Easy");
        catMap.put(italianB, "Italian");
        catMap.put(japaneseB, "Japanese");
        catMap.put(koreanB, "Korean");
        catMap.put(vegetarianB, "Vegetarian");
        for (JRadioButton radioButton : catMap.keySet()) {
            if (radioButton.isSelected()) {
                addCat = catMap.get(radioButton);
                break;
            }
        }
        if(addName.isBlank()){
            JOptionPane.showMessageDialog(this, "Please enter Recipe Name", "Error occurred", JOptionPane.PLAIN_MESSAGE);
        }
        else if(addD.isBlank()){
            JOptionPane.showMessageDialog(this, "Please enter Description", "Error occurred", JOptionPane.PLAIN_MESSAGE);
        }
        else if(addIn.isBlank()){
            JOptionPane.showMessageDialog(this, "Please enter Ingredients", "Error occurred", JOptionPane.PLAIN_MESSAGE);
        }
        else if(addM.isBlank()){
            JOptionPane.showMessageDialog(this, "Please enter Method", "Error occurred", JOptionPane.PLAIN_MESSAGE);
        }
        else if(addCat==null){
            JOptionPane.showMessageDialog(this, "Please select Category", "Error occurred", JOptionPane.PLAIN_MESSAGE);
        }
        else{
            try {
                Connection conn = ComputerScienceIA.connection();
                String insertQuery = "INSERT INTO recipe VALUES (?, ?, ?, ?, ?)";
                PreparedStatement insertStatement = conn.prepareStatement(insertQuery);
                insertStatement.setString(1, addName);
                insertStatement.setString(2, addD);
                insertStatement.setString(3, addIn);
                insertStatement.setString(4, addM);
                insertStatement.setString(5, addCat);
                insertStatement.executeUpdate();
                this.setVisible(false);
            } catch (Exception e) {
                e.printStackTrace();
                System.out.println("Error occurred");
            }
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void chineseBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chineseBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chineseBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addRecipe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JRadioButton britishB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton chineseB;
    private javax.swing.JTextField descriptionF;
    private javax.swing.JRadioButton europeanB;
    private javax.swing.JButton exitButton;
    private javax.swing.JRadioButton fastB;
    private javax.swing.JTextField ingredientsF;
    private javax.swing.JRadioButton italianB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton japaneseB;
    private javax.swing.JRadioButton koreanB;
    private javax.swing.JTextArea methodF;
    private javax.swing.JTextField nameF;
    private javax.swing.JRadioButton vegetarianB;
    // End of variables declaration//GEN-END:variables
}
