/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.yvonne.computerscienceia;

import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.simple.parser.ParseException;

public class HomePage extends javax.swing.JFrame {
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        recipesLabel = new javax.swing.JLabel();
        categories = new javax.swing.JLabel();
        chineseCuisine = new javax.swing.JButton();
        italianCuisine = new javax.swing.JButton();
        europeanCuisine = new javax.swing.JButton();
        vegetarianCuisine = new javax.swing.JButton();
        fastCuisine = new javax.swing.JButton();
        britishCuisine = new javax.swing.JButton();
        japaneseCuisine = new javax.swing.JButton();
        koreanCuisine = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        recipeSearchfield = new javax.swing.JTextField();
        savedRecipe = new javax.swing.JButton();
        addR = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel9.setText("Asian");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(254, 127, 0));

        recipesLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        recipesLabel.setForeground(new java.awt.Color(255, 255, 255));
        recipesLabel.setText("Recipes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(recipesLabel)
                .addContainerGap(279, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(recipesLabel)
                .addGap(28, 28, 28))
        );

        recipesLabel.getAccessibleContext().setAccessibleName("HomeTitle");

        categories.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        categories.setForeground(new java.awt.Color(0, 0, 0));
        categories.setText("Categories");

        chineseCuisine.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        chineseCuisine.setForeground(new java.awt.Color(254, 127, 0));
        chineseCuisine.setText("Chinese");
        chineseCuisine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chineseCuisineActionPerformed(evt);
            }
        });

        italianCuisine.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        italianCuisine.setForeground(new java.awt.Color(254, 127, 0));
        italianCuisine.setText("Italian");
        italianCuisine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                italianCuisineActionPerformed(evt);
            }
        });

        europeanCuisine.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        europeanCuisine.setForeground(new java.awt.Color(254, 127, 0));
        europeanCuisine.setText("European");
        europeanCuisine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                europeanCuisineActionPerformed(evt);
            }
        });

        vegetarianCuisine.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        vegetarianCuisine.setForeground(new java.awt.Color(254, 127, 0));
        vegetarianCuisine.setText("Vegetarian");
        vegetarianCuisine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vegetarianCuisineActionPerformed(evt);
            }
        });

        fastCuisine.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        fastCuisine.setForeground(new java.awt.Color(254, 127, 0));
        fastCuisine.setText("Fast&Easy");
        fastCuisine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fastCuisineActionPerformed(evt);
            }
        });

        britishCuisine.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        britishCuisine.setForeground(new java.awt.Color(254, 127, 0));
        britishCuisine.setText("British");
        britishCuisine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                britishCuisineActionPerformed(evt);
            }
        });

        japaneseCuisine.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        japaneseCuisine.setForeground(new java.awt.Color(254, 127, 0));
        japaneseCuisine.setText("Japanese");
        japaneseCuisine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                japaneseCuisineActionPerformed(evt);
            }
        });

        koreanCuisine.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        koreanCuisine.setForeground(new java.awt.Color(254, 127, 0));
        koreanCuisine.setText("Korean");
        koreanCuisine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                koreanCuisineActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        welcomeLabel.setText("Welcome");

        usernameLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(0, 0, 0));
        usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        String text = LoginPage.username;
        usernameLabel.setText(text);

        recipeSearchfield.setForeground(new java.awt.Color(70, 73, 75));
        recipeSearchfield.setText("Search recipes");
        recipeSearchfield.setToolTipText("");
        recipeSearchfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recipeSearchfieldActionPerformed(evt);
            }
        });

        savedRecipe.setText("Saved Recipe");
        savedRecipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savedRecipeActionPerformed(evt);
            }
        });

        if(!LoginPage.userType.equals("Admin")){
            addR.setVisible(false);
        }
        addR.setText("Add Recipe");
        addR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(welcomeLabel))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(recipeSearchfield, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(savedRecipe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(usernameLabel)
                .addGap(26, 26, 26))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(welcomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameLabel)
                .addGap(29, 29, 29)
                .addComponent(recipeSearchfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(addR)
                .addGap(18, 18, 18)
                .addComponent(savedRecipe)
                .addGap(51, 51, 51))
        );

        jButton1.setText("Get Meal Plan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Your Daily Meal Plan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(britishCuisine)
                                .addGap(18, 18, 18)
                                .addComponent(japaneseCuisine)
                                .addGap(18, 18, 18)
                                .addComponent(koreanCuisine))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(vegetarianCuisine)
                                .addGap(18, 18, 18)
                                .addComponent(fastCuisine))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(categories)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(chineseCuisine)
                                        .addGap(18, 18, 18)
                                        .addComponent(italianCuisine)))
                                .addGap(18, 18, 18)
                                .addComponent(europeanCuisine))
                            .addComponent(jButton1)
                            .addComponent(jLabel1))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(categories)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chineseCuisine)
                    .addComponent(italianCuisine)
                    .addComponent(europeanCuisine))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vegetarianCuisine)
                    .addComponent(fastCuisine))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(britishCuisine)
                    .addComponent(japaneseCuisine)
                    .addComponent(koreanCuisine))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1))
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openRecipe(String cuisineName) {
        recipeCategory dialog = new recipeCategory(cuisineName);
        dialog.setVisible(true);
        dialog.setLocationRelativeTo(this);
    }

    private void chineseCuisineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chineseCuisineActionPerformed
        openRecipe("Chinese");
    }//GEN-LAST:event_chineseCuisineActionPerformed

    private void italianCuisineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_italianCuisineActionPerformed
        openRecipe("Italian");
    }//GEN-LAST:event_italianCuisineActionPerformed

    private void europeanCuisineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_europeanCuisineActionPerformed
        openRecipe("European");
    }//GEN-LAST:event_europeanCuisineActionPerformed

    private void vegetarianCuisineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vegetarianCuisineActionPerformed
        openRecipe("Vegetarian");
    }//GEN-LAST:event_vegetarianCuisineActionPerformed


    private void recipeSearchfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recipeSearchfieldActionPerformed
        String search = recipeSearchfield.getText();
        searchResult newSearch = new searchResult(search);
        newSearch.setVisible(true);
        newSearch.setLocationRelativeTo(this);

    }//GEN-LAST:event_recipeSearchfieldActionPerformed

    private void savedRecipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savedRecipeActionPerformed
        saveRecipe saved = new saveRecipe();
        saved.setVisible(true);
        saved.setLocationRelativeTo(this);
    }//GEN-LAST:event_savedRecipeActionPerformed

    private void fastCuisineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fastCuisineActionPerformed
        openRecipe("Fast&Easy");
    }//GEN-LAST:event_fastCuisineActionPerformed

    private void britishCuisineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_britishCuisineActionPerformed
        openRecipe("British");
    }//GEN-LAST:event_britishCuisineActionPerformed

    private void japaneseCuisineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_japaneseCuisineActionPerformed
        openRecipe("Japanese");
    }//GEN-LAST:event_japaneseCuisineActionPerformed

    private void koreanCuisineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_koreanCuisineActionPerformed
        openRecipe("Korean");
    }//GEN-LAST:event_koreanCuisineActionPerformed

    private void addRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRActionPerformed
        addRecipe add = new addRecipe();
        add.setVisible(true);
        add.setLocationRelativeTo(this);
    }//GEN-LAST:event_addRActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        mealPlans dayPlan = new mealPlans();
        try {
            dayPlan.generateDayMealPlan();
        } catch (ParseException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addR;
    private javax.swing.JButton britishCuisine;
    private javax.swing.JLabel categories;
    private javax.swing.JButton chineseCuisine;
    private javax.swing.JButton europeanCuisine;
    private javax.swing.JButton fastCuisine;
    private javax.swing.JButton italianCuisine;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton japaneseCuisine;
    private javax.swing.JButton koreanCuisine;
    private javax.swing.JTextField recipeSearchfield;
    private javax.swing.JLabel recipesLabel;
    private javax.swing.JButton savedRecipe;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JButton vegetarianCuisine;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
